import pandas as pd
import sys
import os
import pathlib
import subprocess
import argparse
import glob
import csv



'''
Purpose of this program is the following:
First, to look through the "Comparison" data folder for csvs and to merge them into a temporary combined file
Second, using the dataframe generated by the above process, to take the individual target accession number and genome acc
Third, using the number(s), search through the proteomes in order to find the fasta sequence that matches the IDs
Fourth, extract the fasta sequence and store it temporarily in memory
Fifth, using the fasta sequence, run the interproscan program on the fasta file using pfam settings
Sixth, take the output of the interproscan and save it to a directory with species accession number tied to the result
Seventh, 







'''



def runInterproScan (fastaFile, outputDirectory):
    # Purpose of this function is to run the interproscan program using an inputted fasta file
    # Must have an alias that points to the interproscan program for this to work
    # Alias must be interpro. We want the input, model to use, output format to give

    fastaFilename = fastaFile.stem

    output_filename = f'{fastaFilename}.tsv'
    output_filepath = os.path.join(outputDirectory, output_filename)



    command = ["interpro", f"-i {fastaFile}", "-"]

    with open(output_filepath, "w") as outfile:
        subprocess.run(command, stdout=outfile)






